### ISSUE TITLE
program name format overwrites global css

### ISSUE THREAD

**Issue by boynextdoor-cze** [OpenSIST/OpenSIST.github.io#10]
![image](https://github.com/OpenSIST/OpenSIST.github.io/assets/75151020/8d2c26fc-828c-40db-971d-c371897aa891)

**Comment by cuttle-fish-my** [comment]
fixed in [cd4f8ed](https://github.com/OpenSIST/OpenSIST.github.io/commit/cd4f8ed573464835752c1f3ea3f56ce10fa5eb83)
