### ISSUE TITLE
Github-style dialog for confirming deletions.

### ISSUE THREAD

**Issue by caoster** [OpenSIST/OpenSIST.github.io#28]
<img width="514" alt="image" src="https://github.com/OpenSIST/OpenSIST.github.io/assets/78583195/993bf478-349f-4a4a-bb81-d234d691927e">

**Comment by boynextdoor-cze** [comment]
resolved in [cb547a5](https://github.com/OpenSIST/OpenSIST.github.io/commit/cb547a5a3b1b8f96e4961cc67e8ad942c34ff85a).
